theme: jekyll-theme-minimal
logo: "/assets/img/pople5.png"
email: "ramakrishnan@tifrh.res.in"
github: moldis-group
show_downloads: true
classes: wide
---
toc: true
toc_label: "My Table of Contents"
toc_icon: "cog"
---

